In [1]:
import pandas as pd
import os
import numpy as np

# Get statistics reports from sklearn
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report

In [2]:
# Set inputs 


# Read results from the specified files
results_dir = r'C:\Users\mfarj\Documents\projects\aigoeswild\results'
results_file = 'Baseline_model_test_predictions.csv'

In [3]:

predictions_df = pd.read_csv(os.path.join(results_dir, results_file))
# Show initial outputs from the predictions file
print(f"Predictions head:\n{predictions_df.head()}")
print(f"Predictions columns:\n{predictions_df.columns}")


Predictions head:
                                          image_path  true_label  \
0  b'C:\\Users\\mfarj\\Documents\\ss_data\\snapsh...           0   
1  b'C:\\Users\\mfarj\\Documents\\ss_data\\snapsh...           0   
2  b'C:\\Users\\mfarj\\Documents\\ss_data\\snapsh...           2   
3  b'C:\\Users\\mfarj\\Documents\\ss_data\\snapsh...          14   
4  b'C:\\Users\\mfarj\\Documents\\ss_data\\snapsh...           1   

   predicted_label  
0                0  
1                0  
2                1  
3               14  
4                1  
Predictions columns:
Index(['image_path', 'true_label', 'predicted_label'], dtype='object')


In [4]:
# Get true labels and predicted labels from the predictions_df
true_labels = predictions_df.true_label
predicted_labels = predictions_df.predicted_label
print(f"Len True Labels: {len(true_labels)}")
print(f"Len Model Predictions: {len(predicted_labels)}")

Len True Labels: 19377
Len Model Predictions: 19377


In [7]:
np.unique(range(53))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52])

In [9]:
class_accuracies = {}
for class_ in np.unique(range(53)):
    class_acc = np.mean(predicted_labels[true_labels == class_] == class_)
    class_accuracies[].append(class_acc)

In [17]:
def indices(l, val):
    retval = []
    last = 0
    while val in l[last:]:
        i = l[last:].index(val)
        retval.append(last + i)
        last += i + 1   
    return retval

def class_accuracy(y_pred, y_true, label):
    index = indices(l, label)
    y_pred, y_true = ypred[index], y_true[index]
    tp = [1 for k in range(len(y_pred)) if y_true[k]==y_pred[k]]
    tp = np.sum(tp)
    return tp/float(len(y_pred))

In [14]:
class_accuracies

[0.9601455267074582,
 0.9377192982456141,
 0.6530612244897959,
 0.528,
 0.6325757575757576,
 0.0,
 0.6902356902356902,
 0.6630901287553648,
 0.7627551020408163,
 0.2857142857142857,
 0.28,
 0.43097643097643096,
 0.7551020408163265,
 0.9077733860342556,
 0.43137254901960786,
 0.19047619047619047,
 0.2727272727272727,
 0.23404255319148937,
 0.7671232876712328,
 0.0,
 0.4444444444444444,
 0.1111111111111111,
 0.0,
 0.0,
 0.3389830508474576,
 0.5533333333333333,
 0.3,
 0.6140350877192983,
 0.6825396825396826,
 0.20689655172413793,
 0.0851063829787234,
 1.0,
 0.2,
 0.36666666666666664,
 0.6338983050847458,
 0.8111111111111111,
 0.8421052631578947,
 0.0,
 0.2222222222222222,
 0.16666666666666666,
 0.0,
 0.0,
 0.5370370370370371,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan]

In [15]:
cm.diagonal()

array([0.96014553, 0.9377193 , 0.65306122, 0.528     , 0.63257576,
       0.        , 0.69023569, 0.66309013, 0.7627551 , 0.28571429,
       0.28      , 0.43097643, 0.75510204, 0.90777339, 0.43137255,
       0.19047619, 0.27272727, 0.23404255, 0.76712329, 0.        ,
       0.44444444, 0.11111111, 0.        , 0.        , 0.33898305,
       0.55333333, 0.3       , 0.61403509, 0.68253968, 0.20689655,
       0.08510638, 1.        , 0.2       , 0.36666667, 0.63389831,
       0.81111111, 0.84210526, 0.        , 0.22222222, 0.16666667,
       0.        , 0.        , 0.53703704, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [11]:
# Calculate and display statistics
test_accuracy = accuracy_score(true_labels,
                               predicted_labels)
precision = precision_score(true_labels, predicted_labels, average='macro', zero_division=0)
recall = recall_score(true_labels, predicted_labels, average='macro', zero_division=0)
f1 = f1_score(true_labels, predicted_labels, average='macro')


print(f"The accuracy on test set is: {test_accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 score: {f1}")

The accuracy on test set is: 0.8495123084068741
Precision: 0.5054934528992346
Recall: 0.35575091617927157
F1 score: 0.3944040147382305


In [12]:
cm = confusion_matrix(true_labels, predicted_labels)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
#array([[1.        , 0.        , 0.        ],
#      [1.        , 0.        , 0.        ],
#      [0.        , 0.33333333, 0.66666667]])

#The diagonal entries are the accuracies of each class
cm.diagonal()
print(f"Confusion Matrix: \n{cm}")
print(f"Confusion Matrix Diagonal: \n{cm.diagonal()}")



Confusion Matrix: 
[[9.60145527e-01 1.86869522e-02 3.47279643e-03 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [3.79385965e-02 9.37719298e-01 6.57894737e-04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.91836735e-01 2.24489796e-02 6.53061224e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
Confusion Matrix Diagonal: 
[0.96014553 0.9377193  0.65306122 0.528      0.63257576 0.
 0.69023569 0.66309013 0.7627551  0.28571429 0.28       0.43097643
 0.75510204 0.90777339 0.43137255 0.19047619 0.27272727 0.23404255
 0.76712329 0.         0.44444444 0.11111111 0.         0.
 0.33898305 0.55333333 0.3        0.61403509 0.68253968 0.20689655
 0.08510638 1.         0.2        

In [21]:
cm[0][0]

array([7.49462543e-01, 2.66247726e-02, 1.19398049e-01, 0.00000000e+00,
       8.26856292e-04, 1.65371258e-04, 3.83661320e-02, 2.84438565e-02,
       3.63816769e-03, 0.00000000e+00, 1.81908384e-03, 2.64594014e-03,
       3.30742517e-04, 3.63816769e-03, 4.63039524e-03, 0.00000000e+00,
       1.65371258e-04, 1.32297007e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       4.96113775e-04, 6.44947908e-03, 8.26856292e-04, 1.65371258e-04,
       3.30742517e-04, 8.26856292e-04, 0.00000000e+00, 1.32297007e-03,
       1.65371258e-04, 1.98445510e-03, 1.98445510e-03, 0.00000000e+00,
       2.14982636e-03, 0.00000000e+00, 1.32297007e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.96113775e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [37]:
cr = classification_report(true_labels, predicted_labels, digits=3, zero_division=0, output_dict=True)
prediction_report = pd.DataFrame(cr).transpose()
prediction_report = prediction_report[prediction_report.index.astype('str').str.isnumeric()]
prediction_report['class'] = prediction_report.index
prediction_report['class'] = prediction_report['class'].apply(lambda x: x if x.isnumeric() else 99)
prediction_report['class'] = prediction_report['class'].astype(np.int32)
prediction_report['accuracy'] = cm.diagonal()
print(f"Classification report: \n{prediction_report}")

Classification report: 
    precision    recall  f1-score  support  class  accuracy
0    0.874735  0.749463  0.807268   6047.0      0  0.749463
1    0.930098  0.878289  0.903451   4560.0      1  0.878289
2    0.300735  0.834694  0.442162    490.0      2  0.834694
3    0.870370  0.376000  0.525140    125.0      3  0.376000
4    0.788732  0.424242  0.551724    264.0      4  0.424242
5    0.000000  0.000000  0.000000      5.0      5  0.000000
6    0.544457  0.835017  0.659136    594.0      6  0.835017
7    0.338798  0.798283  0.475703    466.0      7  0.798283
8    0.672065  0.846939  0.749436    392.0      8  0.846939
9    0.692308  0.642857  0.666667     14.0      9  0.642857
10   0.602837  0.566667  0.584192    150.0     10  0.566667
11   0.603774  0.323232  0.421053    297.0     11  0.323232
12   0.787149  0.571429  0.662162    343.0     12  0.571429
13   0.930456  0.817918  0.870565   3795.0     13  0.817918
14   0.312693  0.565826  0.402792    357.0     14  0.565826
15   0.333333  0

In [29]:
specie_mapping_file = r"C:\Users\mfarj\Documents\ss_data\data_csv\label_to_species_mapping.csv"
species_mapping = pd.read_csv(specie_mapping_file)
print(f"Species mapping: \n{species_mapping}")

Species mapping: 
   question__species  encoded_species
0           aardvark               32
1           aardwolf               21
2             baboon                3
3        batEaredFox               16
4            buffalo                2
5           bushbuck               45
6            caracal               49
7             cattle               40
8            cheetah               29
9              civet               22
10            dikDik               18
11            duiker               23
12             eland               33
13          elephant                6
14     gazelleGrants               14
15   gazelleThomsons               13
16             genet               48
17           giraffe                8
18        guineaFowl               28
19              hare               20
20        hartebeest               34
21      hippopotamus               36
22       honeyBadger               19
23      hyenaSpotted                4
24      hyenaStriped            

In [38]:
# Merge with classification report
prediction_report = pd.merge(left=prediction_report,right=species_mapping, how="left", left_on="class",
                             right_on="encoded_species", sort=True)
del prediction_report["encoded_species"]
del prediction_report["class"]
del prediction_report["support"]
print(f"Classification report: \n{prediction_report}")

Classification report: 
    precision    recall  f1-score  accuracy question__species
0    0.874735  0.749463  0.807268  0.749463        wildebeest
1    0.930098  0.878289  0.903451  0.878289             zebra
2    0.300735  0.834694  0.442162  0.834694           buffalo
3    0.870370  0.376000  0.525140  0.376000            baboon
4    0.788732  0.424242  0.551724  0.424242      hyenaSpotted
5    0.000000  0.000000  0.000000  0.000000           leopard
6    0.544457  0.835017  0.659136  0.835017          elephant
7    0.338798  0.798283  0.475703  0.798283           warthog
8    0.672065  0.846939  0.749436  0.846939           giraffe
9    0.692308  0.642857  0.666667  0.642857         porcupine
10   0.602837  0.566667  0.584192  0.566667        lionFemale
11   0.603774  0.323232  0.421053  0.323232         otherBird
12   0.787149  0.571429  0.662162  0.571429            impala
13   0.930456  0.817918  0.870565  0.817918   gazelleThomsons
14   0.312693  0.565826  0.402792  0.565826   

In [39]:
# Read number of images of each specie and join it with predictions
file_train_count_specie = r"C:\Users\mfarj\Documents\ss_data\data_csv\train_count_per_species.csv"
count_species = pd.read_csv(file_train_count_specie)

# Merge with classification report
prediction_report = pd.merge(left=prediction_report,right=count_species, how="inner", left_on="question__species",
                             right_on="question__species")
prediction_report = prediction_report.sort_values('count', ascending=False)
print(f"Classification report: \n{prediction_report}")

Classification report: 
    precision    recall  f1-score  accuracy question__species  count
51   0.000000  0.000000  0.000000  0.000000           rodents      1
50   0.000000  0.000000  0.000000  0.000000           zorilla      5
48   0.000000  0.000000  0.000000  0.000000             genet      8
44   0.000000  0.000000  0.000000  0.000000           wildcat      8
22   0.000000  0.000000  0.000000  0.000000             civet     11
49   0.000000  0.000000  0.000000  0.000000           caracal     14
19   0.000000  0.000000  0.000000  0.000000       honeyBadger     14
31   0.066667  1.000000  0.125000  1.000000        rhinoceros     15
47   0.000000  0.000000  0.000000  0.000000          steenbok     15
46   0.000000  0.000000  0.000000  0.000000          reptiles     17
40   0.000000  0.000000  0.000000  0.000000            cattle     27
23   0.000000  0.000000  0.000000  0.000000            duiker     29
41   1.000000  0.333333  0.500000  0.333333      hyenaStriped     29
43   0.000

In [33]:
# Rearrange columns
cols = prediction_report.columns.tolist()
cols = cols[-1:] + cols[:-1]
prediction_report = prediction_report.reindex(columns=cols)
prediction_report
# prediction_report.to_csv(os.path.join(results_dir, fn_predicted_report), sep=',', header=True, index=False)

question__species  precision    recall  f1-score  accuracy
0         wildebeest   0.874735  0.749463  0.807268  0.749463
1              zebra   0.930098  0.878289  0.903451  0.878289
2            buffalo   0.300735  0.834694  0.442162  0.834694
3             baboon   0.870370  0.376000  0.525140  0.376000
4       hyenaSpotted   0.788732  0.424242  0.551724  0.424242
5            leopard   0.000000  0.000000  0.000000  0.000000
6           elephant   0.544457  0.835017  0.659136  0.835017
7            warthog   0.338798  0.798283  0.475703  0.798283
8            giraffe   0.672065  0.846939  0.749436  0.846939
9          porcupine   0.692308  0.642857  0.666667  0.642857
10        lionFemale   0.602837  0.566667  0.584192  0.566667
11         otherBird   0.603774  0.323232  0.421053  0.323232
12            impala   0.787149  0.571429  0.662162  0.571429
13   gazelleThomsons   0.930456  0.817918  0.870565  0.817918
14     gazelleGrants   0.312693  0.565826  0.402792  0.565826
15          mongoose   0.333333  0.190476  0.242424  0.190476
16       batEaredFox   0.384615  0.454545  0.416667  0.454545
17            jackal   0.183673  0.191489  0.187500  0.191489
18            dikDik   0.766667  0.630137  0.691729  0.630137
19       honeyBadger   0.000000  0.000000  0.000000  0.000000
20              hare   0.606061  0.740741  0.666667  0.740741
21          aardwolf   0.500000  0.111111  0.181818  0.111111
22             civet   0.000000  0.000000  0.000000  0.000000
23            duiker   0.000000  0.000000  0.000000  0.000000
24           ostrich   0.451613  0.237288  0.311111  0.237288
25              topi   0.400000  0.520000  0.452174  0.520000
26            serval   0.206349  0.433333  0.279570  0.433333
27          reedbuck   0.894737  0.596491  0.715789  0.596491
28        guineaFowl   0.759036  0.666667  0.709859  0.666667
29           cheetah   0.545455  0.310345  0.395604  0.310345
30      insectSpider   0.384615  0.319149  0.348837  0.319149
31        rhinoceros   0.066667  1.000000  0.125000  1.000000
32          aardvark   0.300000  0.300000  0.300000  0.300000
33             eland   0.618421  0.522222  0.566265  0.522222
34        hartebeest   0.715640  0.511864  0.596838  0.511864
35     secretaryBird   0.912500  0.811111  0.858824  0.811111
36      hippopotamus   0.795181  0.868421  0.830189  0.868421
37      vervetMonkey   0.000000  0.000000  0.000000  0.000000
38         waterbuck   0.090909  0.111111  0.100000  0.111111
39          lionMale   0.636364  0.194444  0.297872  0.194444
40            cattle   0.000000  0.000000  0.000000  0.000000
41      hyenaStriped   1.000000  0.333333  0.500000  0.333333
42       koriBustard   0.547619  0.425926  0.479167  0.425926
43           vulture   0.000000  0.000000  0.000000  0.000000
44           wildcat   0.000000  0.000000  0.000000  0.000000
45          bushbuck   0.500000  0.250000  0.333333  0.250000
46          reptiles   0.000000  0.000000  0.000000  0.000000
47          steenbok   0.000000  0.000000  0.000000  0.000000
48             genet   0.000000  0.000000  0.000000  0.000000
49           caracal   0.000000  0.000000  0.000000  0.000000
50           zorilla   0.000000  0.000000  0.000000  0.000000
51           rodents   0.000000  0.000000  0.000000  0.000000